{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "e3f01186_5c408f50",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1000579
      },
      "writtenOn": "2022-01-31T17:16:13Z",
      "side": 1,
      "message": "fastbootd works fine here because we have a recovery check already",
      "revId": "d6cc5c7962a3893f7cdf88972efc4042c45e18d8",
      "serverId": "3162e3d8-d894-470e-abd9-724f7b0effad"
    }
  ]
}